### ISSUE TITLE
Question: What algorithm did you use for face frontalization?

### ISSUE THREAD

**Issue by dshahrokhian** [melgor/Face-Verification#1]
I stumbled upon this repository when searching for implementations of face frontalization. 

Would you kindly refer to the technique you are using? Is it working?

Thanks,
Dani

**Comment by melgor** [comment]
In this project, I use simple Affine-Projection. Just calculate the Perspective transform.
I have also implemented 3D-Frontalization but overall it had lower accuracy,

**Comment by dshahrokhian** [comment]
@melgor Thank you.
